### ISSUE TITLE
GitHub Actions失敗: actions/upload-artifact@v3非推奨エラー

### ISSUE THREAD

**Issue by meron14725** [meron14725/note-columns-post-bot#43]
## 🚨 問題概要
`Daily Article Collection and Evaluation` ワークフローが失敗しています。

## ❌ エラー内容
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. 
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

## 📍 影響範囲
- **ワークフロー**: `.github/workflows/daily_update.yml`
- **失敗箇所**: `actions/upload-artifact@v3` 使用部分
- **影響**: 日次記事収集・評価処理が実行されない

## 🔧 修正必要箇所
```yaml
# 行 127, 135: v3 → v4 に更新が必要
- name: Upload logs as artifact
  uses: actions/upload-artifact@v3  # ← v4に更新
  
- name: Upload database backup  
  uses: actions/upload-artifact@v3  # ← v4に更新
```

## 📅 発生タイミング
- GitHub Actions実行時
- Runner version: 2.325.0
- 2024年4月16日以降のDeprecation Notice発効後

## ✅ 解決方法
1. `actions/upload-artifact@v3` → `actions/upload-artifact@v4` に更新
2. v4の新しい仕様に合わせて設定調整
3. 動作確認・テスト実行

## 🎯 優先度
**🔴 HIGH** - 日次バッチ処理が停止しているため緊急対応が必要

## 📋 関連情報
- [GitHub Changelog](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
- [actions/upload-artifact v4 docs](https://github.com/actions/upload-artifact)
